language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install: composer install --prefer-dist --no-interaction

before_script: ./vendor/bin/phpcs -n --standard=PSR2 src/ tests/

script: ./vendor/bin/phpunit
